Loading R/3.5.3
  Loading requirement: ompi/3.0.0/gcc/4.8.5
/opt/sge/crc/spool/d12chas352/job_scripts/461804: line 14: python/2.7.15: No such file or directory
google
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "script_google.py", line 1310, in <module>
    sys.exit(main())
  File "script_google.py", line 1293, in main
    querier.send_query(query)
  File "script_google.py", line 1021, in send_query
    html = self._get_http_response(url=query.get_url(),
  File "script_google.py", line 858, in get_url
    urlargs[key] = quote(encode(val))
  File "script_google.py", line 200, in encode
    return s.encode('utf-8') # pylint: disable-msg=C0103
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
